# Generated by Django 3.2 on 2021-04-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contents',
            new_name='content',
        ),
    ]
